[package]
name = "reddit-rs"
version = "0.1.0"
authors = ["saresend <saresend@usc.edu>"]

[dependencies]
reqwest = "0.8.5"
serde = "1.0"
serde_derive = "1.0"
url = "1.7.0"
serde_json = "1.0"
hyper = "0.11.22"

[dev-dependencies]
dotenv = "0.11.0"
